"""Regenerate the broadened-protocol CD diagram (Figure 2 / cd_protocol.pdf).

This script redraws the diagram dynamically from the raw parquet records 
generated by the protocol validation, using the correct Nemenyi CD, matching 
the lur.experiments._cd_diagram style.
"""
import os
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import sys

# Ensure lur is in the path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from lur import stats

# 1. Load the actual protocol raw data
parquet_path = os.path.join(os.path.dirname(__file__), "..", "..", "results", "protocol", "current", "raw", "benchmark.parquet")
if not os.path.exists(parquet_path):
    raise FileNotFoundError(f"Cannot find protocol benchmark data at {parquet_path}")

df = pd.read_parquet(parquet_path)
pivot = df.pivot_table(index=["seed", "geometry", "m", "replication", "dirichlet_alpha"], columns="method", values="tail_loss")

methods = pivot.columns.tolist()
mat = pivot.values

# 2. Compute true ranks and CD
ranks = stats.average_ranks(mat)
k = len(methods)
N = mat.shape[0]
CD = stats.nemenyi_cd(k, N, alpha=0.05)

RANKS = dict(zip(methods, ranks))
names = sorted(RANKS, key=RANKS.get)
r = [RANKS[n] for n in names]

print(f"Generated CD Diagram for {k} methods and {N} instances. CD = {CD:.3f}")

# 3. Plot
fig, ax = plt.subplots(figsize=(8, 2.6))
lo, hi = 1, max(r) + 0.5
ax.set_xlim(lo - 0.5, hi + 0.5)
ax.set_ylim(0, 1)
ax.hlines(0.75, lo, max(r), color="k")

# Stagger labels vertically to avoid overlap among the 14 tightly-packed methods
# We use 3 levels to avoid overlapping when k=14
for i, (nm, rr) in enumerate(zip(names, r)):
    ax.vlines(rr, 0.7, 0.8, color="k")
    level = i % 3
    y = 0.62 - level * 0.12
    ax.vlines(rr, y + 0.08, 0.8, color="0.7", lw=0.5)
    
    fontweight = "bold" if "LUR" in nm else "normal"
    color = "crimson" if "LUR" in nm else "black"
    ax.text(rr, y, f"{nm}\n{rr:.2f}", ha="center", va="top", fontsize=8, 
            fontweight=fontweight, color=color)

ax.plot([lo, lo + CD], [0.92, 0.92], color="crimson", lw=3)
ax.text(lo + CD / 2, 0.95, f"CD={CD:.3f}", ha="center", fontsize=8, color="crimson")
ax.axis("off")
ax.set_title("Average ranks on tail held-out loss (broadened protocol, lower = better)",
             fontsize=9)
fig.tight_layout()

targets = [
    os.path.join(os.path.dirname(__file__), "..", "..", "paper", "cd_protocol.pdf"),
    os.path.join(os.path.dirname(__file__), "..", "..", "results", "protocol", "current",
                 "figures", "cd_protocol.pdf"),
]

for t in targets:
    t = os.path.abspath(t)
    os.makedirs(os.path.dirname(t), exist_ok=True)
    fig.savefig(t)
    print("wrote", t)
plt.close(fig)
